---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    type: db
    author: gina
spec:
  containers:
    - name: mydb
      image: mysql:5
      ports:
        - containerPort: 80
          hostPort: 8080
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
...